### PR TITLE
Add huggingface models and tasks that use gpt2 and robert model type

### PR DESCRIPTION
**Pull request by cli99**
This PR adds all huggingface models that use gpt2 and roberta as the model type, and expands the tasks categories to also include text-classification, token-classification, fill-mask, conversational.
To get the complete list of supported models, you can use https://gist.github.com/cli99/a528999f7e596e1aeba4d14a4657b8f1.

### CODE REVIEW

**Comment by AlexeySlvv** [comment]
> This PR adds all huggingface models that use gpt2 and roberta as the model type, and expands the tasks categories to also include text-classification, token-classification, fill-mask, conversational. To get the complete list of supported models, you can use https://gist.github.com/cli99/a528999f7e596e1aeba4d14a4657b8f1.

So, I didn't get my model in the list. Does it mean that I cannot speed up it with MII?

**Comment by jeffra** [comment]
> > This PR adds all huggingface models that use gpt2 and roberta as the model type, and expands the tasks categories to also include text-classification, token-classification, fill-mask, conversational. To get the complete list of supported models, you can use https://gist.github.com/cli99/a528999f7e596e1aeba4d14a4657b8f1.
> 
> So, I didn't get my model in the list. Does it mean that I cannot speed up it with MII?

Are you trying to use a model from hugging face (HF)? If so can you link the model? We support many different model families that cover thousands of models provided by HF. You can see the list here also: https://github.com/microsoft/DeepSpeed-mii#supported-models-and-tasks

**Comment by AlexeySlvv** [comment]
> > > This PR adds all huggingface models that use gpt2 and roberta as the model type, and expands the tasks categories to also include text-classification, token-classification, fill-mask, conversational. To get the complete list of supported models, you can use https://gist.github.com/cli99/a528999f7e596e1aeba4d14a4657b8f1.
> > 
> > 
> > So, I didn't get my model in the list. Does it mean that I cannot speed up it with MII?
> 
> Are you trying to use a model from hugging face (HF)? If so can you link the model? We support many different model families that cover thousands of models provided by HF. You can see the list here also: https://github.com/microsoft/DeepSpeed-mii#supported-models-and-tasks

Thanks. Yes, I'm trying "sberbank-ai/ruRoberta-large" (fill-mask) and "vicgalle/xlm-roberta-large-xnli-anli" (zero-shot-classification). I reran get_hf_models.py again and now they are in the output list. It is strange.

**Comment by jeffra** [comment]
> > > > This PR adds all huggingface models that use gpt2 and roberta as the model type, and expands the tasks categories to also include text-classification, token-classification, fill-mask, conversational. To get the complete list of supported models, you can use https://gist.github.com/cli99/a528999f7e596e1aeba4d14a4657b8f1.
> > > 
> > > 
> > > So, I didn't get my model in the list. Does it mean that I cannot speed up it with MII?
> > 
> > 
> > Are you trying to use a model from hugging face (HF)? If so can you link the model? We support many different model families that cover thousands of models provided by HF. You can see the list here also: https://github.com/microsoft/DeepSpeed-mii#supported-models-and-tasks
> 
> Thanks. Yes, I'm trying "sberbank-ai/ruRoberta-large" (fill-mask) and "vicgalle/xlm-roberta-large-xnli-anli" (zero-shot-classification). I reran get_hf_models.py again and now they are in the output list. It is strange.


> > > > This PR adds all huggingface models that use gpt2 and roberta as the model type, and expands the tasks categories to also include text-classification, token-classification, fill-mask, conversational. To get the complete list of supported models, you can use https://gist.github.com/cli99/a528999f7e596e1aeba4d14a4657b8f1.
> > > 
> > > 
> > > So, I didn't get my model in the list. Does it mean that I cannot speed up it with MII?
> > 
> > 
> > Are you trying to use a model from hugging face (HF)? If so can you link the model? We support many different model families that cover thousands of models provided by HF. You can see the list here also: https://github.com/microsoft/DeepSpeed-mii#supported-models-and-tasks
> 
> Thanks. Yes, I'm trying "sberbank-ai/ruRoberta-large" (fill-mask) and "vicgalle/xlm-roberta-large-xnli-anli" (zero-shot-classification). I reran get_hf_models.py again and now they are in the output list. It is strange.

Hmm that is odd. Both models you list are based on models we support though. You should be good. Are you seeing an error when trying to deploy with MII? The model config json here: https://huggingface.co/sberbank-ai/ruRoberta-large/blob/main/config.json#L17 maps to the model families I linked previously.

**Comment by AlexeySlvv** [comment]
> > > > > This PR adds all huggingface models that use gpt2 and roberta as the model type, and expands the tasks categories to also include text-classification, token-classification, fill-mask, conversational. To get the complete list of supported models, you can use https://gist.github.com/cli99/a528999f7e596e1aeba4d14a4657b8f1.
> > > > 
> > > > 
> > > > So, I didn't get my model in the list. Does it mean that I cannot speed up it with MII?
> > > 
> > > 
> > > Are you trying to use a model from hugging face (HF)? If so can you link the model? We support many different model families that cover thousands of models provided by HF. You can see the list here also: https://github.com/microsoft/DeepSpeed-mii#supported-models-and-tasks
> > 
> > 
> > Thanks. Yes, I'm trying "sberbank-ai/ruRoberta-large" (fill-mask) and "vicgalle/xlm-roberta-large-xnli-anli" (zero-shot-classification). I reran get_hf_models.py again and now they are in the output list. It is strange.
> 
> > > > > This PR adds all huggingface models that use gpt2 and roberta as the model type, and expands the tasks categories to also include text-classification, token-classification, fill-mask, conversational. To get the complete list of supported models, you can use https://gist.github.com/cli99/a528999f7e596e1aeba4d14a4657b8f1.
> > > > 
> > > > 
> > > > So, I didn't get my model in the list. Does it mean that I cannot speed up it with MII?
> > > 
> > > 
> > > Are you trying to use a model from hugging face (HF)? If so can you link the model? We support many different model families that cover thousands of models provided by HF. You can see the list here also: https://github.com/microsoft/DeepSpeed-mii#supported-models-and-tasks
> > 
> > 
> > Thanks. Yes, I'm trying "sberbank-ai/ruRoberta-large" (fill-mask) and "vicgalle/xlm-roberta-large-xnli-anli" (zero-shot-classification). I reran get_hf_models.py again and now they are in the output list. It is strange.
> 
> Hmm that is odd. Both models you list are based on models we support though. You should be good. Are you seeing an error when trying to deploy with MII? The model config json here: https://huggingface.co/sberbank-ai/ruRoberta-large/blob/main/config.json#L17 maps to the model families I linked previously.

Deploy works good. Maybe I do something wrong with query. I will check it twice!

**Comment by AlexeySlvv** [comment]
OK, I checked twice and wrote this python code:
`import mii

model_name = "vicgalle/xlm-roberta-large-xnli-anli"
model_task = "zero-shot-classification"
mii.deploy(task=model_task, model=model_name, deployment_name="xlm-roberta-large-xnli-anli_deploy")
`
And I got an error: "AssertionError: Unknown Task zero-shot-classification".
I checked the model config: https://huggingface.co/vicgalle/xlm-roberta-large-xnli-anli/blob/main/config.json.
`"model_type": "xlm-roberta"`
So "zero-shot-classification" does not support by now?

**Comment by AlexeySlvv** [comment]
> Hmm that is odd. Both models you list are based on models we support though. You should be good. Are you seeing an error when trying to deploy with MII? The model config json here: https://huggingface.co/sberbank-ai/ruRoberta-large/blob/main/config.json#L17 maps to the model families I linked previously.

I've done with "ruRoberta-large". That was my mistake with queries. So the question only with the "zero-shot-classification" task support with MII.

**Pull request merged**
