### PR TITLE
Adding trust_remote_code support

### PR DESCRIPTION
**Pull request by msinha251**
- [Enhancement](https://github.com/microsoft/DeepSpeed-MII/issues/181)

### CODE REVIEW

**Review by mrwyattii — APPROVED** [review]

**Comment by mrwyattii** [comment]
@msinha251 could you also sign the license agreement? Thank you

**Comment by msinha251** [comment]
> 

@microsoft-github-policy-service agree

**Comment by msinha251** [comment]
> @msinha251 could you also sign the license agreement? Thank you



> @msinha251 could you also sign the license agreement? Thank you

@mrwyattii it's approved and passed all checks. Anything else is pending ?

**Comment by mrwyattii** [comment]
@msinha251 sorry for the delay. Just resolved the merge conflict. Tests and running now and I will merge after they pass. Thank you!

**Pull request merged**
